"""
config.py
=========
Configuration constants for CREMP coral reef analysis project.

Author: Cece Foltz
Date: 03/31/2025
"""

import os
from pathlib import Path

# =============================================================================
# DIRECTORY PATHS
# =============================================================================

# Project root directory (parent of src/)
PROJECT_ROOT = Path(__file__).parent.parent

# Data directories
DATA_DIR = PROJECT_ROOT / 'data'
RAW_DATA_DIR = DATA_DIR / 'raw'
CLEANED_DATA_DIR = DATA_DIR / 'cleaned'

# Output directories
OUTPUTS_DIR = PROJECT_ROOT / 'outputs'
FIGURES_DIR = OUTPUTS_DIR / 'figures'
REPORTS_DIR = OUTPUTS_DIR / 'reports'

# =============================================================================
# DATA FILE NAMES
# =============================================================================

# Raw data files
RAW_FILES = {
    'octo_raw': 'CREMP_OCTO_RawData_2023.csv',
    'octo_density': 'CREMP_OCTO_Summaries_2023_Density.csv',
    'octo_height': 'CREMP_OCTO_Summaries_2023_MeanHeight.csv',
    'pcover_species': 'CREMP_Pcover_2023_StonyCoralSpecies.csv',
    'pcover_taxa': 'CREMP_Pcover_2023_TaxaGroups.csv',
    'scor_raw': 'CREMP_SCOR_RawData_2023.csv',
    'scor_condition': 'CREMP_SCOR_Summaries_2023_ConditionCounts.csv',
    'scor_counts': 'CREMP_SCOR_Summaries_2023_Counts.csv',
    'scor_density': 'CREMP_SCOR_Summaries_2023_Density.csv',
    'scor_lta': 'CREMP_SCOR_Summaries_2023_LTA.csv',
    'stations': 'CREMP_Stations_2023.csv',
    'temperatures': 'CREMP_Temperatures_2023.csv'
}

# Cleaned data files (generated by cleaning pipeline)
CLEANED_FILES = {
    key: name.replace('.csv', '_Cleaned.csv')
    for key, name in RAW_FILES.items()
}

# =============================================================================
# METADATA COLUMNS
# =============================================================================

# Columns that are metadata (not species/measurement data)
METADATA_COLUMNS = [
    'OID_', 'Year', 'Date', 'Subregion', 'Habitat',
    'SiteID', 'Site_name', 'StationID', 'Surveyed_all_years', 'points',
    'Lat', 'Lon', 'Latitude', 'Longitude', 'Depth', 'Depth_m'
]

# =============================================================================
# CLEANING PARAMETERS
# =============================================================================

# Columns that can have IQR outlier removal applied
# ONLY unbounded physical measurements
IQR_OUTLIER_COLUMNS = [
    'Diameter_cm',
    'Height_cm',
    'Max_Diameter',
    'Perp_Diameter'
]

# Columns where negative values are physically impossible
NON_NEGATIVE_COLUMNS = [
    'LTA', 'Diameter_cm', 'Height_cm',
    'Density', 'Count', 'TempC'
]

# IQR multiplier for outlier detection
IQR_MULTIPLIER = 1.5

# =============================================================================
# ANALYSIS PARAMETERS
# =============================================================================

# Chunk size for large file processing
CHUNK_SIZE = 100_000

# Future prediction years
PREDICTION_YEARS_AHEAD = 10

# Confidence interval level
CONFIDENCE_LEVEL = 0.95

# =============================================================================
# VISUALIZATION SETTINGS
# =============================================================================

# Figure size defaults
FIG_SIZE_SINGLE = (12, 6)
FIG_SIZE_DOUBLE = (16, 6)
FIG_SIZE_TALL = (15, 12)

# Color palettes
SUBREGION_PALETTE = 'Set2'
HABITAT_PALETTE = 'Set3'

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_raw_filepath(file_key: str) -> Path:
    """
    Get full path to a raw data file.
    
    Args:
        file_key: Key from RAW_FILES dict or filename
    
    Returns:
        Path object to the raw file
    """
    filename = RAW_FILES.get(file_key, file_key)
    return RAW_DATA_DIR / filename


def get_cleaned_filepath(file_key: str) -> Path:
    """
    Get full path to a cleaned data file.
    
    Args:
        file_key: Key from CLEANED_FILES dict or filename
    
    Returns:
        Path object to the cleaned file
    """
    filename = CLEANED_FILES.get(file_key, file_key)
    return CLEANED_DATA_DIR / filename


def ensure_directories():
    """Create all required directories if they don't exist."""
    directories = [
        RAW_DATA_DIR,
        CLEANED_DATA_DIR,
        FIGURES_DIR,
        REPORTS_DIR
    ]
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
        print(f"Ensured directory exists: {directory}")


# =============================================================================
# MAIN - Print configuration when run directly
# =============================================================================

if __name__ == "__main__":
    print("CREMP Coral Reef Analysis - Configuration")
    print("=" * 50)
    print(f"Project Root:     {PROJECT_ROOT}")
    print(f"Raw Data Dir:     {RAW_DATA_DIR}")
    print(f"Cleaned Data Dir: {CLEANED_DATA_DIR}")
    print(f"Figures Dir:      {FIGURES_DIR}")
    print(f"Reports Dir:      {REPORTS_DIR}")
    print(f"\nMetadata Columns: {len(METADATA_COLUMNS)}")
    print(f"Raw Files:        {len(RAW_FILES)}")
    print(f"Chunk Size:       {CHUNK_SIZE:,}")
